Repository usgs/earthquake-eventpages, pull requests merged in 2018-03, with the labels that each got.

#787 Issue 753
  src/app/origin/magnitude-detail/magnitude-detail.component.css
  src/app/origin/magnitude-detail/magnitude-detail.component.html
  src/app/origin/magnitude-detail/magnitude-detail.component.spec.ts
  src/app/origin/magnitude-detail/magnitude-detail.component.ts
  src/app/origin/magnitude/magnitude.component.css
  src/app/origin/magnitude/magnitude.component.html
  src/app/origin/magnitude/magnitude.component.spec.ts
  src/app/origin/magnitude/magnitude.component.ts
  src/app/origin/origin.module.ts
  src/app/origin/origin/origin.component.html
  src/app/origin/phase/phase.component.html
  src/app/origin/phase/phase.component.spec.ts
  src/app/origin/phase/phase.component.ts
  src/app/product-page/product-page.module.ts
  src/app/quakeml-testdata-nc72923380.ts
  src/app/quakeml-testdata-uu60268292.ts
  src/app/quakeml.spec.ts
  src/app/quakeml.ts
Labels: needs review

#788 Origin Pin Fixes
  src/app/executive/executive/executive.component.html
  src/app/executive/executive/executive.component.spec.ts
  src/app/executive/origin-pin/origin-pin.component.html
  src/app/executive/origin-pin/origin-pin.component.spec.ts
  src/app/executive/origin-pin/origin-pin.component.ts
  src/app/formatter.service.ts
Labels: needs review

#789 Beachball
  src/app/app-routing.module.ts
  src/app/event-page/navigation/navigation.component.html
  src/app/moment-tensor/axes/axes.component.css
  src/app/moment-tensor/axes/axes.component.html
  src/app/moment-tensor/axes/axes.component.spec.ts
  src/app/moment-tensor/axes/axes.component.ts
  src/app/moment-tensor/info/info.component.css
  src/app/moment-tensor/info/info.component.html
  src/app/moment-tensor/info/info.component.spec.ts
  src/app/moment-tensor/info/info.component.ts
  src/app/moment-tensor/moment-tensor-routing.module.ts
  src/app/moment-tensor/moment-tensor.module.ts
  src/app/moment-tensor/moment-tensor/moment-tensor.component.css
  src/app/moment-tensor/moment-tensor/moment-tensor.component.html
  src/app/moment-tensor/moment-tensor/moment-tensor.component.spec.ts
  src/app/moment-tensor/moment-tensor/moment-tensor.component.ts
  src/app/moment-tensor/nodal-planes/nodal-planes.component.css
  src/app/moment-tensor/nodal-planes/nodal-planes.component.html
  src/app/moment-tensor/nodal-planes/nodal-planes.component.spec.ts
  src/app/moment-tensor/nodal-planes/nodal-planes.component.ts
  src/app/shared/beachball/beachball.component.css
  src/app/shared/beachball/beachball.component.html
  src/app/shared/beachball/beachball.component.spec.ts
  src/app/shared/beachball/beachball.component.ts
  src/app/shared/beachball/beachball.spec.ts
  src/app/shared/beachball/beachball.ts
  src/app/shared/beachball/canvas.spec.ts
  src/app/shared/beachball/canvas.ts
  src/app/shared/beachball/matrix.spec.ts
  src/app/shared/beachball/matrix.ts
  src/app/shared/beachball/tensor.spec.ts
  src/app/shared/beachball/tensor.ts
  src/app/shared/beachball/vector.spec.ts
  src/app/shared/beachball/vector.ts
  src/app/shared/product-attribution/product-attribution.component.css
  src/app/shared/product-attribution/product-attribution.component.html
  src/app/shared/product-attribution/product-attribution.component.spec.ts
  src/app/shared/product-attribution/product-attribution.component.ts
  src/app/shared/shared.module.ts
  src/app/technical/moment-tensor-summary/moment-tensor-summary.component.css
  src/app/technical/moment-tensor-summary/moment-tensor-summary.component.html
  src/app/technical/moment-tensor-summary/moment-tensor-summary.component.spec.ts
  src/app/technical/moment-tensor-summary/moment-tensor-summary.component.ts
  src/app/technical/origin-summary/origin-summary.component.css
  src/app/technical/origin-summary/origin-summary.component.html
  src/app/technical/origin-summary/origin-summary.component.spec.ts
  src/app/technical/origin-summary/origin-summary.component.ts
  src/app/technical/technical.module.ts
  src/app/technical/technical/technical.component.html
  src/app/technical/technical/technical.component.spec.ts
  src/app/technical/technical/technical.component.ts
Labels: needs review

#796 Issue-751
  proxy.conf.js
  src/app/app.module.ts
  src/app/contents-xml.service.ts
  src/app/formatter.service.spec.ts
  src/app/formatter.service.ts
  src/app/geoserve.service.spec.ts
  src/app/geoserve.service.ts
  src/app/origin/detail/detail.component.css
  src/app/origin/detail/detail.component.html
  src/app/origin/detail/detail.component.spec.ts
  src/app/origin/detail/detail.component.ts
  src/app/product-page/download/download.component.css
  src/app/product-page/footer/footer.component.css
  src/app/shared/attribution/attribution.component.css
  src/app/shared/attribution/attribution.component.html
  src/app/shared/attribution/attribution.component.spec.ts
  src/app/shared/attribution/attribution.component.ts
  src/app/shared/coordinates/coordinates.component.css
  src/app/shared/coordinates/coordinates.component.html
  src/app/shared/coordinates/coordinates.component.spec.ts
  src/app/shared/coordinates/coordinates.component.ts
  src/app/shared/fe-region/fe-region.component.css
  src/app/shared/fe-region/fe-region.component.html
  src/app/shared/fe-region/fe-region.component.spec.ts
  src/app/shared/fe-region/fe-region.component.ts
  src/app/shared/product-attribution/product-attribution.component.html
  src/app/shared/product-attribution/product-attribution.component.spec.ts
  src/app/shared/product-attribution/product-attribution.component.ts
  src/app/shared/shared.module.ts
  src/app/shared/uncertain-value/uncertain-value.component.css
  src/app/shared/uncertain-value/uncertain-value.component.html
  src/app/shared/uncertain-value/uncertain-value.component.spec.ts
  src/app/shared/uncertain-value/uncertain-value.component.ts
  src/environments/environment.e2e.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: needs review

#792 Issue-746
  src/app/event-page/navigation/navigation.component.spec.ts
  src/app/executive/regional-pin/regional-pin.component.ts
  src/app/moment-tensor/axes/axes.component.spec.ts
Labels: needs review

#798 Issue 753 2
  src/app/executive/executive/executive.component.html
  src/app/executive/executive/executive.component.spec.ts
  src/app/executive/origin-pin/origin-pin.component.html
  src/app/executive/origin-pin/origin-pin.component.spec.ts
  src/app/executive/origin-pin/origin-pin.component.ts
  src/app/executive/regional-pin/regional-pin.component.html
  src/app/executive/regional-pin/regional-pin.component.spec.ts
  src/app/executive/regional-pin/regional-pin.component.ts
  src/app/moment-tensor/axes/axes.component.html
  src/app/moment-tensor/axes/axes.component.spec.ts
  src/app/moment-tensor/axes/axes.component.ts
  src/app/moment-tensor/info/info.component.html
  src/app/moment-tensor/info/info.component.spec.ts
  src/app/moment-tensor/info/info.component.ts
  src/app/moment-tensor/nodal-planes/nodal-planes.component.html
  src/app/moment-tensor/nodal-planes/nodal-planes.component.spec.ts
  src/app/moment-tensor/nodal-planes/nodal-planes.component.ts
  src/app/origin/magnitude-detail/magnitude-detail.component.html
  src/app/origin/magnitude-detail/magnitude-detail.component.ts
  src/app/origin/magnitude/magnitude.component.css
  src/app/origin/magnitude/magnitude.component.html
  src/app/origin/magnitude/magnitude.component.spec.ts
  src/app/origin/magnitude/magnitude.component.ts
  src/app/origin/origin.module.ts
  src/app/origin/origin/origin.component.html
  src/app/origin/phase/phase.component.html
  src/app/origin/phase/phase.component.spec.ts
  src/app/origin/phase/phase.component.ts
  src/app/product-page/contributor-list.pipe.spec.ts
  src/app/product-page/contributor-list.pipe.ts
  src/app/product-page/download/download.component.css
  src/app/product-page/header/header.component.html
  src/app/product-page/header/header.component.spec.ts
  src/app/product-page/product-page.module.ts
  src/app/shared/bubble/bubble.component.css
  src/app/shared/bubble/bubble.component.html
  src/app/shared/bubble/bubble.component.spec.ts
  src/app/shared/bubble/bubble.component.ts
  src/app/shared/degrees.pipe.spec.ts
  src/app/shared/degrees.pipe.ts
  src/app/shared/download-dialog/download-dialog.component.html
  src/app/shared/number.pipe.spec.ts
  src/app/shared/number.pipe.ts
  src/app/shared/shared.module.ts
Labels: needs review

#799 Update Origin-Pin
  src/app/executive/executive/executive.component.html
  src/app/executive/executive/executive.component.spec.ts
  src/app/executive/origin-pin/origin-pin.component.ts
  src/app/formatter.service.ts
Labels: needs review

#802 Description table
  .angular-cli.json
  src/app/moment-tensor/info/info.component.css
  src/app/moment-tensor/info/info.component.html
  src/app/shared/css/description-table.scss
  src/styles.scss
Labels: needs review

#812 removed variable that was not needed in alert-level, added styles and…
  src/app/impact/dyfi-summary/dyfi-summary.component.html
  src/app/shared/alert-level/alert-level.component.html
  src/app/shared/alert-level/alert-level.component.scss
  src/app/shared/alert-level/alert-level.component.spec.ts
  src/app/shared/alert-level/alert-level.component.ts
  src/app/shared/mmi/mmi.component.scss
  src/app/shared/mmi/mmi.component.spec.ts
  src/app/shared/mmi/mmi.component.ts
Labels: needs review

#804 ShakeMap module with ported components
  index.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/core/core.module.ts
  src/app/core/metadata.service.spec.ts
  src/app/core/metadata.service.ts
  src/app/core/station.service.spec.ts
  src/app/core/station.service.ts
  src/app/shakemap/metadata/input/input.component.html
  src/app/shakemap/metadata/input/input.component.scss
  src/app/shakemap/metadata/input/input.component.spec.ts
  src/app/shakemap/metadata/input/input.component.ts
  src/app/shakemap/metadata/metadata.component.css
  src/app/shakemap/metadata/metadata.component.html
  src/app/shakemap/metadata/metadata.component.spec.ts
  src/app/shakemap/metadata/metadata.component.ts
  src/app/shakemap/metadata/output/output.component.html
  src/app/shakemap/metadata/output/output.component.scss
  src/app/shakemap/metadata/output/output.component.spec.ts
  src/app/shakemap/metadata/output/output.component.ts
  src/app/shakemap/metadata/processing/processing.component.html
  src/app/shakemap/metadata/processing/processing.component.scss
  src/app/shakemap/metadata/processing/processing.component.spec.ts
  src/app/shakemap/metadata/processing/processing.component.ts
  src/app/shakemap/shakemap-routing.module.ts
  src/app/shakemap/shakemap.module.ts
  src/app/shakemap/shakemap/shakemap.component.css
  src/app/shakemap/shakemap/shakemap.component.html
  src/app/shakemap/shakemap/shakemap.component.spec.ts
  src/app/shakemap/shakemap/shakemap.component.ts
  src/app/shakemap/station-list/station-list.component.css
  src/app/shakemap/station-list/station-list.component.html
  src/app/shakemap/station-list/station-list.component.spec.ts
  src/app/shakemap/station-list/station-list.component.ts
  src/app/shared/shared.module.ts
  src/app/shared/station/station.component.css
  src/app/shared/station/station.component.html
  src/app/shared/station/station.component.spec.ts
  src/app/shared/station/station.component.ts
Labels: scheduled

#815 Issue-805
  src/app/core/metadata.service.spec.ts
  src/app/core/metadata.service.ts
  src/app/core/station.service.spec.ts
  src/app/core/station.service.ts
  src/app/shakemap/metadata/input/input.component.html
  src/app/shakemap/metadata/metadata.component.spec.ts
  src/app/shakemap/metadata/metadata.component.ts
  src/app/shakemap/metadata/output/output.component.html
  src/app/shakemap/metadata/processing/processing.component.html
  src/app/shakemap/station-list/station-list.component.spec.ts
  src/app/shakemap/station-list/station-list.component.ts
  src/app/shared/station/station.component.html
Labels: needs review

#822 Issue 819
  src/app/executive/executive.module.ts
  src/app/executive/executive/executive.component.html
  src/app/executive/executive/executive.component.spec.ts
  src/app/executive/focal-mechanism-pin/focal-mechanism-pin.component.html
  src/app/executive/focal-mechanism-pin/focal-mechanism-pin.component.scss
  src/app/executive/focal-mechanism-pin/focal-mechanism-pin.component.spec.ts
  src/app/executive/focal-mechanism-pin/focal-mechanism-pin.component.ts
Labels: needs review

#814 Issue-755
  .dockerignore
  Dockerfile
  Jenkinsfile.groovy
  README.md
  docker-entrypoint.sh
  metadata.json
  package-lock.json
  package.json
Labels: needs review

#828 cleaned up code, added else for moment tensor
  src/app/executive/executive/executive.component.html
  src/app/executive/focal-mechanism-pin/focal-mechanism-pin.component.spec.ts
  src/app/executive/focal-mechanism-pin/focal-mechanism-pin.component.ts
Labels: needs review

#824 Shakemap Metadata Improvements
  src/app/core/formatter.service.spec.ts
  src/app/core/formatter.service.ts
  src/app/shakemap/metadata/input/input.component.html
  src/app/shakemap/metadata/input/input.component.spec.ts
  src/app/shakemap/metadata/input/input.component.ts
  src/app/shakemap/metadata/metadata.component.html
  src/app/shakemap/metadata/metadata.component.ts
  src/app/shakemap/metadata/output/output.component.html
  src/app/shakemap/metadata/output/output.component.spec.ts
  src/app/shakemap/metadata/output/output.component.ts
  src/app/shakemap/metadata/processing/processing.component.html
  src/app/shakemap/metadata/processing/processing.component.spec.ts
  src/app/shakemap/metadata/processing/processing.component.ts
  src/app/shakemap/shakemap/shakemap.component.ts
  src/app/shared/date.pipe.spec.ts
  src/app/shared/date.pipe.ts
  src/app/shared/location.pipe.spec.ts
  src/app/shared/location.pipe.ts
  src/app/shared/shared.module.ts
  src/app/shared/units.pipe.spec.ts
  src/app/shared/units.pipe.ts
Labels: needs review

#830 Issue-816
  src/app/executive/basic-pin/basic-pin.component.css
  src/app/executive/basic-pin/basic-pin.component.html
  src/app/executive/basic-pin/basic-pin.component.scss
  src/app/executive/basic-pin/basic-pin.component.ts
  src/app/executive/executive.module.ts
  src/app/executive/executive/executive.component.html
  src/app/executive/executive/executive.component.scss
  src/app/executive/focal-mechanism-pin/focal-mechanism-pin.component.spec.ts
  src/app/executive/moment-tensor-pin/moment-tensor-pin.component.spec.ts
  src/app/executive/origin-pin/origin-pin.component.html
  src/app/executive/origin-pin/origin-pin.component.scss
  src/app/executive/origin-pin/origin-pin.component.spec.ts
  src/app/executive/region-info-pin/region-info-pin.component.css
  src/app/executive/region-info-pin/region-info-pin.component.html
  src/app/executive/region-info-pin/region-info-pin.component.ts
Labels: needs review

#829 Issue-810
  src/app/origin/detail/detail.component.html
  src/app/origin/detail/detail.component.spec.ts
  src/app/origin/detail/detail.component.ts
Labels: needs review

#827 Package upgrades
  Jenkinsfile.groovy
  package-lock.json
  package.json
  src/app/core/event.service.spec.ts
  src/app/core/geoserve.service.spec.ts
  src/app/core/station.service.spec.ts
  src/app/shared/beachball/beachball.spec.ts
Labels: in review

#832 Fix Build
  Dockerfile
Labels: needs review

#833 Adding git to unit test runner container.
  Jenkinsfile.groovy
Labels: needs review

#837 Using tar.gz for zone.js dependency
  Dockerfile
  Jenkinsfile.groovy
  package-lock.json
  package.json
Labels: needs review

#842 Issue 818
  src/app/core/event.service.ts
  src/app/technical/focal-mechanism-summary/focal-mechanism-summary.component.html
  src/app/technical/focal-mechanism-summary/focal-mechanism-summary.component.scss
  src/app/technical/focal-mechanism-summary/focal-mechanism-summary.component.spec.ts
  src/app/technical/focal-mechanism-summary/focal-mechanism-summary.component.ts
  src/app/technical/technical.module.ts
  src/app/technical/technical/technical.component.html
  src/app/technical/technical/technical.component.spec.ts
Labels: needs review

#835 Improve handling of old shakemap products
  index.ts
  src/app/core/metadata.service.spec.ts
  src/app/core/metadata.service.ts
  src/app/core/station.service.spec.ts
  src/app/core/station.service.ts
  src/app/shakemap/shakemap.module.ts
Labels: needs review

#843 Metadata
  src/app/core/formatter.service.spec.ts
  src/app/core/formatter.service.ts
  src/app/shakemap/metadata/input/input.component.html
  src/app/shakemap/metadata/input/input.component.spec.ts
  src/app/shakemap/metadata/input/input.component.ts
  src/app/shakemap/metadata/metadata.component.html
  src/app/shakemap/metadata/output/output.component.html
  src/app/shakemap/metadata/output/output.component.spec.ts
  src/app/shakemap/metadata/output/output.component.ts
  src/app/shakemap/metadata/processing/processing.component.html
  src/app/shakemap/metadata/processing/processing.component.spec.ts
  src/app/shakemap/metadata/processing/processing.component.ts
  src/app/shared/date-time.pipe.spec.ts
  src/app/shared/date-time.pipe.ts
  src/app/shared/degrees.pipe.spec.ts
  src/app/shared/degrees.pipe.ts
  src/app/shared/shared.module.ts
  src/app/shared/units.pipe.spec.ts
Labels: needs review

#839 Issue-806
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/event-page/navigation/navigation.component.html
  src/app/map/map.module.ts
  src/app/map/map/map.component.html
  src/app/map/map/map.component.scss
  src/app/map/map/map.component.spec.ts
  src/app/map/map/map.component.ts
  src/app/region-info/region-info/region-info.component.ts
  src/app/shared/map/map.component.html
  src/app/shared/map/map.component.scss
  src/app/shared/map/map.component.spec.ts
  src/app/shared/map/map.component.ts
  src/app/shared/shared.module.ts
Labels: needs review

#841 Uncertainty component working
  src/app/shakemap/shakemap-routing.module.ts
  src/app/shakemap/shakemap.module.ts
  src/app/shakemap/shakemap/shakemap.component.html
  src/app/shakemap/uncertainty/uncertainty.component.html
  src/app/shakemap/uncertainty/uncertainty.component.scss
  src/app/shakemap/uncertainty/uncertainty.component.spec.ts
  src/app/shakemap/uncertainty/uncertainty.component.ts
Labels: needs review

#845 Add Quality Statement Styles
  src/app/product-page/header/header.component.css
  src/app/product-page/header/header.component.scss
  src/app/product-page/header/header.component.ts
Labels: needs review

#875 Issue 861
  src/app/executive/executive/executive.component.html
  src/app/executive/executive/executive.component.spec.ts
  src/app/executive/region-info-pin/region-info-pin.component.html
  src/app/executive/region-info-pin/region-info-pin.component.spec.ts
  src/app/shared/get-product.pipe.spec.ts
  src/app/shared/get-product.pipe.ts
  src/app/shared/shared.module.ts
Labels: needs review
